apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodejs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nodejs-app
  template:
    metadata:
      labels:
        app: my-nodejs-app
    spec:
      containers:
      - name: mynodejsdockerrepo
        image: containerregistryimage.azurecr.io/imagenodejsexample:latest
        ports:
        - containerPort: 5000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: my-nodejs-app-svc
spec:
  selector:
    app: my-nodejs-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer